when:
  branch:
    exclude: pages
  event: [push, pull_request]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: python:bookworm
    commands:
      - python3 _util/main.py
      - date > out/generated-at.txt
    when:
      event: [pull_request, push]

  publish-codeberg:
    image: bitnami/git
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      # Git configuration
      - git config --global user.email "robot@example.com"
      - git config --global user.name "Builder bot"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git _out_repo
      - rm -r _out_repo/*
      # Copy build step output to repository folder
      - cp -r out/. _out_repo/
      # Needed for custom domains
      - cp .domains _out_repo || true # Ignore if it doesn't exist
      # Commit and push all static files with pipeline started timestamp
      - cd _out_repo
      - git add .
      - git commit -m "Automatic rebuild for ${CI_COMMIT_SHA}"
      - git push
    when:
      event: push
